### ISSUE TITLE
yarn run prod gives error

### ISSUE THREAD

**Issue by huggla** [qgis/qwc2#33]
Row 7 in package-commands.sh:
`NODE_ENV='production' webpack`
Gives the following error:

> ERROR in webpack-dev-server.js from UglifyJs
> Unexpected token: name (urlParts) [webpack-dev-server.js:8349,4]

Building with latest node and yarn on Ubuntu 17.04

**Comment by andreasneumann** [comment]
@huggla - Thanks for your report!

please report issues on QWC2 at https://github.com/qgis/qwc2-demo-app/issues 

I am closing this here and will disable issues on this repo.
